name: appimage-installer
title: AppImage-Installer
version: '1.0.0-alpha'
summary: Install and manage AppImages
description: |
  Manage all of your AppImages in a simple but feature rich tool.

base: core24
grade: stable
confinement: strict

license: MIT
contact: primula99@outlook.de
issues: https://github.com/Anton-Lindauer/AppImage-Installer/issues
source-code: https://github.com/Anton-Lindauer/AppImage-Installer
website: https://github.com/Anton-Lindauer/AppImage-Installer

platforms:
  amd64:

icon: snap/gui/appimage-installer_icon.svg

plugs:

  dot-config-appimage-installer:
    interface: personal-files
    write:
      - $HOME/.config

  dot-local-share-appimage-installer:
    interface: personal-files
    write:
      - $HOME/.local/share

  dot-local-bin-appimage-installer:
    interface: personal-files
    write:
      - $HOME/.local/bin

apps:
  appimage-installer:
    command: bin/python3 $SNAP/main.py

    environment:
      HOME: $SNAP_REAL_HOME
      PYTHONPATH: $SNAP:$PYTHONPATH
      QT_PLUGIN_PATH: $SNAP_DESKTOP_RUNTIME/usr/lib/qt6/plugins:$QT_PLUGIN_PATH

    extensions:
      - kde-neon-6

    plugs:
      - home
      - removable-media
      - dot-config-appimage-installer
      - dot-local-share-appimage-installer
      - dot-local-bin-appimage-installer

parts:
  python-runtime:
    plugin: nil
    stage-packages:
      - libpython3.12-minimal
      - libpython3.12-stdlib
      - python3-minimal
      - python3.12-minimal
      - python3.12-venv
      - locales

  appimage-installer-deps:
    after:
      - python-runtime
    plugin: python
    source: .
    python-packages:
      - PySide6==6.11.1

    override-prime: |
      craftctl default

      QT="$CRAFT_PRIME/lib/python3.12/site-packages/PySide6/Qt"

      rm -f "$QT/lib/libQt63D"*
      rm -f "$QT/lib/libQt6Charts"*
      rm -f "$QT/lib/libQt6DataVisualization"*
      rm -f "$QT/lib/libQt6Designer"*
      rm -f "$QT/lib/libQt6Graphs"*
      rm -f "$QT/lib/libQt6Location"*
      rm -f "$QT/lib/libQt6Multimedia"*
      rm -f "$QT/lib/libQt6NetworkAuth"*
      rm -f "$QT/lib/libQt6Pdf"*
      rm -f "$QT/lib/libQt6PdfWidgets"*
      rm -f "$QT/lib/libQt6Positioning"*
      rm -f "$QT/lib/libQt6Quick"*
      rm -f "$QT/lib/libQt6Quick3D"*
      rm -f "$QT/lib/libQt6QuickControls2"*
      rm -f "$QT/lib/libQt6QuickTemplates2"*
      rm -f "$QT/lib/libQt6QuickTest"*
      rm -f "$QT/lib/libQt6QuickWidgets"*
      rm -f "$QT/lib/libQt6RemoteObjects"*
      rm -f "$QT/lib/libQt6Scxml"*
      rm -f "$QT/lib/libQt6Sensors"*
      rm -f "$QT/lib/libQt6SerialBus"*
      rm -f "$QT/lib/libQt6SerialPort"*
      rm -f "$QT/lib/libQt6SpatialAudio"*
      rm -f "$QT/lib/libQt6StateMachine"*
      rm -f "$QT/lib/libQt6TextToSpeech"*
      rm -f "$QT/lib/libQt6VirtualKeyboard"*
      rm -f "$QT/lib/libQt6WebChannel"*
      rm -f "$QT/lib/libQt6WebEngine"*
      rm -f "$QT/lib/libQt6WebSockets"*
      rm -f "$QT/lib/libQt6WebView"*

      rm -rf "$QT/plugins/sqldrivers"
      rm -rf "$QT/plugins/geoservices"
      rm -rf "$QT/plugins/position"
      rm -rf "$QT/plugins/multimedia"
      rm -rf "$QT/plugins/webview"
      rm -rf "$QT/plugins/renderers"
      rm -rf "$QT/plugins/sceneparsers"

      rm -f "$QT/plugins/imageformats/libqtiff.so"

  app-code:
    plugin: dump
    source: .
    stage:
      - main.py
      - src/
      - assets/
      - translations/

  licenses:
    plugin: dump
    source: .
    organize:
      THIRD_PARTY_LICENSES.md: usr/share/doc/appimage-installer/THIRD_PARTY_LICENSES.md
    stage:
      - usr/share/doc/appimage-installer/THIRD_PARTY_LICENSES.md