name: appimage-installer
base: core24
version: '0.1-alpha'
summary: Install and manage AppImages
description: |
  Manage all of your AppImages in a simple but feature rich tool.

grade: devel
confinement: devmode
platforms:
  amd64:

apps:
  appimage-installer:
    command: bin/python3 $SNAP/main.py
    environment:
      HOME: $SNAP_REAL_HOME
      PYTHONPATH: $SNAP:$PYTHONPATH
      QT_PLUGIN_PATH: $SNAP_DESKTOP_RUNTIME/usr/lib/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - home
      - removable-media

icon: snap/gui/appimage-installer_icon.svg

parts:
  python-runtime:
    plugin: nil
    stage-packages:
      - libpython3.12-minimal
      - libpython3.12-stdlib
      - python3-minimal
      - python3.12-minimal
      - python3.12-venv
      - locales

  appimage-installer-deps:
    after: [python-runtime]
    plugin: python
    source: .
    python-packages:
      - PySide6==6.11.1

  app-code:
    plugin: dump
    source: .
    stage:
      - main.py
      - src/
      - assets/
      - translations/